# Generated by Django 3.2.9 on 2022-01-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='variants',
            field=models.ManyToManyField(blank=True, related_name='_product_product_variants_+', to='product.Product'),
        ),
    ]
